<a href="https://colab.research.google.com/github/Viplaw7/A-Research-Paper/blob/main/ICTP_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Multiplication using TensorFlow on the GPU

In [ ]:
import tensorflow as tf
import numpy as np

# Create input matrices
x = tf.constant(np.arange(16).reshape([4, 4]), dtype=tf.float32)
y = tf.constant(np.ones([4, 4]), dtype=tf.float32)

# Perform matrix multiplication on GPU
z = tf.linalg.matmul(x, y)

# Convert result to NumPy array and print
print("Result from TensorFlow matrix multiplication:")
print(z.numpy())

Result from TensorFlow matrix multiplication:
[[ 6.  6.  6.  6.]
 [22. 22. 22. 22.]
 [38. 38. 38. 38.]
 [54. 54. 54. 54.]]


In [ ]:
import tensorflow as tf
import numpy as np

# Create input matrices with different values
x = tf.constant(np.arange(1, 17).reshape([4, 4]), dtype=tf.float32)  # Matrix with values from 1 to 16
y = tf.constant(np.arange(17, 33).reshape([4, 4]), dtype=tf.float32) # Matrix with values from 17 to 32



# Convert result to NumPy array and print
print("Matrix x:")
print(x.numpy())

print("\nMatrix y:")
print(y.numpy())

Matrix x:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Matrix y:
[[17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]]


In [ ]:
import tensorflow as tf
import numpy as np

# Create input matrices
x = tf.constant(np.arange(9).reshape([3, 3]), dtype=tf.float32)
y = tf.constant(np.ones([3, 3]), dtype=tf.float32)

# Perform matrix multiplication on GPU
z = tf.linalg.matmul(x, y)

# Convert result to NumPy array and print
print("Result from TensorFlow matrix multiplication:")
print(z.numpy())

Result from TensorFlow matrix multiplication:
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [ ]:
import tensorflow as tf
import numpy as np

# Create input matrices
x = tf.constant(np.arange(4).reshape([2, 2]), dtype=tf.float32)
y = tf.constant(np.ones([2, 2]), dtype=tf.float32)

# Perform matrix multiplication on GPU
z = tf.linalg.matmul(x, y)

# Convert result to NumPy array and print
print("Result from TensorFlow matrix multiplication:")
print(z.numpy())

Result from TensorFlow matrix multiplication:
[[1. 1.]
 [5. 5.]]


In [ ]:
import tensorflow as tf
import numpy as np

# Create input matrices with different data types
x = tf.constant(np.arange(16).reshape([4, 4]), dtype=tf.float16)  # Change dtype to float16
y = tf.constant(np.ones([4, 4]), dtype=tf.float16)                # Change dtype to float16

# Perform matrix multiplication on GPU
with tf.device('/device:GPU:0'):
    z = tf.matmul(x, y)

# Convert result to NumPy array and print
print("Result from TensorFlow matrix multiplication:")
print(z.numpy())


Result from TensorFlow matrix multiplication:
[[ 6.  6.  6.  6.]
 [22. 22. 22. 22.]
 [38. 38. 38. 38.]
 [54. 54. 54. 54.]]


# use the CuPy library

In [ ]:
!pip install cupy


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 14.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cupy
  Running setup.py clean for cupy
Failed to build cupy
ERROR: Could not build wheels for cupy, which is required to install pyproject.toml-based projects


In [ ]:
import cupy as cp
import numpy as np

# Create input matrices
x = cp.arange(16).reshape([4, 4])
y = cp.ones([4, 4])

# Perform matrix multiplication on GPU
z = cp.matmul(x, y)

# Convert result to NumPy array and print
print("Result from CuPy matrix multiplication:")
print(cp.asnumpy(z))


Result from CuPy matrix multiplication:
[[ 6.  6.  6.  6.]
 [22. 22. 22. 22.]
 [38. 38. 38. 38.]
 [54. 54. 54. 54.]]


In [ ]:
import cupy as cp
import numpy as np

# Create input matrices with different values
x_np = np.arange(1, 17).reshape([4, 4]).astype(np.float32)  # Matrix with values from 1 to 16
y_np = np.arange(17, 33).reshape([4, 4]).astype(np.float32) # Matrix with values from 17 to 32

x = cp.array(x_np)
y = cp.array(y_np)

# Print the matrices
print("Matrix x:")
print(cp.asnumpy(x))

print("\nMatrix y:")
print(cp.asnumpy(y))


Matrix x:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Matrix y:
[[17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]]


In [ ]:
import cupy as cp
import numpy as np

# Create input matrices
x = cp.arange(9).reshape([3, 3])
y = cp.ones([3, 3])

# Perform matrix multiplication on GPU
z = cp.matmul(x, y)

# Convert result to NumPy array and print
print("Result from CuPy matrix multiplication:")
print(cp.asnumpy(z))


Result from CuPy matrix multiplication:
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


#use NumPy

In [ ]:
import numpy as np

# Create input matrices with float32 data type
x = np.arange(16, dtype=np.float32).reshape([4, 4])  # Matrix with values from 0 to 15
y = np.ones([4, 4], dtype=np.float32)               # Matrix of ones

# Print the matrices
print("Matrix x:")
print(x)

print("\nMatrix y:")
print(y)


Matrix x:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

Matrix y:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

# Create input matrices
x = np.arange(16).reshape([4, 4])  # Example matrix with values from 0 to 15
y = np.ones([4, 4])                 # Matrix of ones

# Print the matrices
print("Matrix x:")
print(x)

print("\nMatrix y:")
print(y)


Matrix x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Matrix y:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#represent matrices using Numba

In [ ]:
import numpy as np
from numba import njit

# Define a Numba JIT-compiled function to create input matrices
@njit
def create_matrices():
    x = np.arange(16, dtype=np.float32).reshape((4, 4))  # Matrix with values from 0 to 15
    y = np.ones((4, 4), dtype=np.float32)               # Matrix of ones
    return x, y

# Create input matrices
x, y = create_matrices()

# Print the matrices
print("Matrix x:")
print(x)

print("\nMatrix y:")
print(y)


Matrix x:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

Matrix y:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#**Matrix** **Representation**

In [ ]:
import math
from numba import cuda
import numpy as np

@cuda.jit
def matmul(x, y, out):
    start_x, start_y = cuda.grid(2)
    stride_x, stride_y = cuda.gridsize(2)
    for i in range(start_x, x.shape[0], stride_x):
        for j in range(start_y, y.shape[1], stride_y):
            tmp = 0
            for k in range(x.shape[1]):
                tmp += x[i, k] * y[k, j]
            out[i, j] = tmp

x_h = np.arange(16).reshape([4, 4])
  y_h = np.ones([4, 4])
z_h = np.zeros([4, 4])

# Moving numpy arrays to GPU
x_d = cuda.to_device(x_h)
y_d = cuda.to_device(y_h)
z_d = cuda.to_device(z_h)

# Defining the grid on the GPU, using 32 threads per block
threadsperblock = (32, 32)
blockspergrid_x = math.ceil(z_h.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(z_h.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Performing the matmul
matmul[blockspergrid, threadsperblock](x_d, y_d, z_d)

# Copying the output array back to the CPU
z_h = z_d.copy_to_host()

print(z_h)


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[ 6.  6.  6.  6.]
 [22. 22. 22. 22.]
 [38. 38. 38. 38.]
 [54. 54. 54. 54.]]


In [ ]:
import math
from numba import cuda
import numpy as np

@cuda.jit
def matmul(x, y, out):
    start_x, start_y = cuda.grid(2)
    stride_x, stride_y = cuda.gridsize(2)
    for i in range(start_x, x.shape[0], stride_x):
        for j in range(start_y, y.shape[1], stride_y):
            tmp = 0
            for k in range(x.shape[1]):
                tmp += x[i, k] * y[k, j]
            out[i, j] = tmp

@cuda.jit
def scale_matrix(matrix, scalar):
    x, y = cuda.grid(2)
    if x < matrix.shape[0] and y < matrix.shape[1]:
        matrix[x, y] *= scalar

x_h = np.arange(16).reshape([4, 4])
y_h = np.ones([4, 4])
z_h = np.zeros([4, 4])

# Moving numpy arrays to GPU
x_d = cuda.to_device(x_h)
y_d = cuda.to_device(y_h)
z_d = cuda.to_device(z_h)

# Defining the grid on the GPU, using 32 threads per block
threadsperblock = (32, 32)
blockspergrid_x = math.ceil(z_h.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(z_h.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Performing the matmul
matmul[blockspergrid, threadsperblock](x_d, y_d, z_d)

# Scaling the resulting matrix
scale_factor = 2
scale_matrix[blockspergrid, threadsperblock](z_d, scale_factor)

# Copying the output array back to the CPU
z_h = z_d.copy_to_host()

print(z_h)


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[ 12.  12.  12.  12.]
 [ 44.  44.  44.  44.]
 [ 76.  76.  76.  76.]
 [108. 108. 108. 108.]]


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


In [ ]:
import math
from numba import cuda
import numpy as np

@cuda.jit
def matmul(x, y, out):
    start_x, start_y = cuda.grid(2)
    stride_x, stride_y = cuda.gridsize(2)
    for i in range(start_x, x.shape[0], stride_x):
        for j in range(start_y, y.shape[1], stride_y):
            tmp = 0
            for k in range(x.shape[1]):
                tmp += x[i, k] * y[k, j]
            out[i, j] = tmp

@cuda.jit
def scale_matrix(matrix, scalar):
    x, y = cuda.grid(2)
    if x < matrix.shape[0] and y < matrix.shape[1]:
        matrix[x, y] *= scalar

x_h = np.arange(16).reshape([4, 4])
y_h = np.ones([4, 4])
z_h = np.zeros([4, 4])

# Moving numpy arrays to GPU
x_d = cuda.to_device(x_h)
y_d = cuda.to_device(y_h)
z_d = cuda.to_device(z_h)

# Defining the grid on the GPU, using 32 threads per block
threadsperblock = (32, 32)
blockspergrid_x = math.ceil(z_h.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(z_h.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Performing the matmul
matmul[blockspergrid, threadsperblock](x_d, y_d, z_d)

# Scaling the resulting matrix
scale_factor = 2.5
scale_matrix[blockspergrid, threadsperblock](z_d, scale_factor)

# Copying the output array back to the CPU
z_h = z_d.copy_to_host()

print(z_h)


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[ 15.  15.  15.  15.]
 [ 55.  55.  55.  55.]
 [ 95.  95.  95.  95.]
 [135. 135. 135. 135.]]


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


In [ ]:
import math
from numba import cuda
import numpy as np

@cuda.jit
def matmul(x, y, out):
    start_x, start_y = cuda.grid(2)
    stride_x, stride_y = cuda.gridsize(2)
    for i in range(start_x, x.shape[0], stride_x):
        for j in range(start_y, y.shape[1], stride_y):
            tmp = 0
            for k in range(x.shape[1]):
                tmp += x[i, k] * y[k, j]
            out[i, j] = tmp

@cuda.jit
def scale_matrix(matrix, scalar):
    x, y = cuda.grid(2)
    if x < matrix.shape[0] and y < matrix.shape[1]:
        matrix[x, y] *= scalar

@cuda.jit
def add_scalar(matrix, scalar):
    x, y = cuda.grid(2)
    if x < matrix.shape[0] and y < matrix.shape[1]:
        matrix[x, y] += scalar

x_h = np.arange(16).reshape([4, 4])
y_h = np.ones([4, 4])
z_h = np.zeros([4, 4])

# Moving numpy arrays to GPU
x_d = cuda.to_device(x_h)
y_d = cuda.to_device(y_h)
z_d = cuda.to_device(z_h)

# Defining the grid on the GPU, using 32 threads per block
threadsperblock = (32, 32)
blockspergrid_x = math.ceil(z_h.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(z_h.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Performing the matmul
matmul[blockspergrid, threadsperblock](x_d, y_d, z_d)

# Scaling the resulting matrix
scale_factor = 2
scale_matrix[blockspergrid, threadsperblock](z_d, scale_factor)

# Adding a scalar value to the resulting matrix
scalar_value = 5
add_scalar[blockspergrid, threadsperblock](z_d, scalar_value)

# Copying the output array back to the CPU
z_h = z_d.copy_to_host()

print(z_h)


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[ 17.  17.  17.  17.]
 [ 49.  49.  49.  49.]
 [ 81.  81.  81.  81.]
 [113. 113. 113. 113.]]
